config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'
  
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create]
    end
  end
end

  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  belongs_to :post

  validates :text, presence: true

  after_save :update_post_comment_counter

  private

  def update_post_comment_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :update_post_like_counter

  private

  def update_post_like_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  before_create :set_default_values
  belongs_to :author, class_name: 'User', counter_cache: true
  has_many :comments
  has_many :likes

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_user_post_counter

  def most_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def set_default_values
    self.comments_counter ||= 0
    self.likes_counter ||= 0
  end

  def update_user_post_counter
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, foreign_key: :author_id
  has_many :comments
  has_many :likes

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def most_recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post_and_user, only: [:new, :create]

  def new
    @comment = Comment.new
  end

  def create
    @comment = @post.comments.build(comment_params)
    @comment.author = current_user

    if @comment.save
      redirect_to user_posts_path(@user), notice: 'Comment was successfully created.'
    else
      redirect_to user_posts_path(@user), alert: 'Error creating comment.'
    end
  end

  private

  def set_post_and_user
    @post = Post.find(params[:post_id])
    @user = @post.author
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_user_and_post, only: [:create]

  def create
    if @post.likes.exists?(user: @user)
      redirect_to user_posts_path(@user), alert: 'You have already liked this post.'
    else
      @like = @post.likes.build(user: @user)

      if @like.save
        redirect_to user_posts_path(@user), notice: 'Post liked successfully.'
      else
        redirect_to user_posts_path(@user), alert: 'Error liking the post.'
      end
    end
  end

  private

  def set_user_and_post
    @user = current_user
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_user

  def index
    @posts = @user.posts
  end

  def show
    @post = @user.posts.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    comment_count = 0
    likes_count = 0

    @post = current_user.posts.build(post_params)
    @post.comments_counter = comment_count
    @post.likes_counter = likes_count

    if @post.save
      redirect_to user_posts_path(current_user)
    else
      render :new
    end
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<h1>Add New Comment!</h1>
<hr class="col-md-6 mb-5">


<%= form_with(model: @comment, url: user_post_comments_path(@user, @post)) do |form| %>

  <div class="col-md-6 mb-3">
    <%= form.label :text, style: "display: block",class: "fw-bold form-label" %>
    <%= form.text_area :text, class: "form-control", placeholder: "Comment", rows: "3" %>
  </div>

  <div class="mb-3">
    <%= form.submit "Add Comment", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<%= stylesheet_link_tag 'posts_index' %>

<div class="user-show-container">
  <div class="user-image-container">
    <img src="<%= @user.photo %>" alt="<%= @user.name %>">
  </div>

  <div class="user-details-container">
    <h1><%= @user.name %></h1>
    <p class="post-count">Number of posts: <%= @user.posts.count %></p>
  </div>
</div>

div class="user-posts-container">
  <ul>
    <% @user.posts.includes(:comments, :likes, :author).each do |post| %>
      <li>
        <h2>
          <%= link_to post.title, user_post_path(@user, post) %>
        </h2>

        <%= "#{post.text}" %>
        <p class="post-metadata">
          <span class="comments-count">Comments: <%= post.comments.count %></span>
          <span class="likes-count">Likes: <%= post.likes.count %></span>
        </p>

        <ul class="comments-list">
          <% post.most_recent_comments.each do |comment| %>
            <li>
              <strong><%= comment.author.name %>:</strong> <%= comment.text %>
            </li>
          <% end %>
        </ul>
      </li>
    <% end %>
  </ul>
</div>

<div class="last-btn">
  <button class="back-link">Pagination</button>
</div>

app/views/posts/new.html.erb
<h1>Create New Post!</h1>
<hr class="col-md-6 mb-5">


<%= form_with(model: [@user, @post], url: user_posts_path(@user)) do |form| %>

  <div class="col-md-6 mb-3">
    <%= form.label :title, style: "display: block",class: "fw-bold form-label" %>
    <%= form.text_field :title, class: "form-control", placeholder: "Title" %>
  </div>

  <div class="col-md-6 mb-3">
    <%= form.label :text, style: "display: block",class: "fw-bold form-label" %>
    <%= form.text_area :text, class: "form-control", placeholder: "Content", rows: "3" %>
  </div>


<div class="mb-3">
<%= form.submit "Create Post", class: 'btn btn-primary' %>
</div>
<% end %>

app/views/posts/show.html.erb
<%= stylesheet_link_tag 'posts_show' %>

<div class="post-container">
  <h1>
    <% post_count = @user.posts.count %>
    <% if post_count.zero? %>
      No Posts
    <% elsif post_count == 1 %>
      Post #1
    <% else %>
      <%= "Post ##{post_count}" %>
    <% end %>
    by <%= @user.name %>
  </h1>

  <div class="comments-likes">
    <p>
      <strong>Comments: <%= @post.comments_counter %></strong>,
      <strong>Likes: <%= @post.likes_counter %></strong>
      <%= form_with(url: user_post_likes_path(@user, @post), method: :post, local: true, class: 'like-form') do |form| %>
        <%= form.submit 'Like', class: 'like-button' %>
      <% end %>
    </p>
  </div>
</div>

<p class="post-text"><%= @post.text %></p>

<div class="user-comments-container">
  <ul>
    <% @post.comments.includes(:author).each do |comment| %>
      <li>
        <strong><%= comment.author.name %>:</strong> <%= comment.text %>
      </li>
    <% end %>
  </ul>
</div>

<%= link_to 'Back', user_posts_path(@user), class: 'back-link' %>

app/views/users/index.html.erb
<%= stylesheet_link_tag 'user_index' %>

<% if @users.any? %>
  <div class="user-list">
    <% @users.includes(:posts).each do |user| %>
      <div class="user-item">
        <div class="user-image-container">
          <% if user.photo.present? %>
            <img src="<%= user.photo %>" alt="<%= user.name %>">
          <% end %>
        </div>
        <div class="user-details-container">
          <h2>
            <%= link_to user.name, user_path(user.id) %>
          </h2>
          <p class="post-count">Number of posts: <%= user.posts.count %></p>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <p class="no-users">No users found.</p>
<% end %>

app/views/users/show.html.erb
<%= stylesheet_link_tag 'user_show' %>

<div class="user-show-container">
  <div class="user-image-container">
    <img src="<%= @user.photo %>" alt="<%= @user.name %>">
  </div>

  <div class="user-details-container">
    <h1><%= @user.name %></h1>
    <p class="post-count">Number of posts: <%= @user.posts.count %></p>
  </div>
</div>

<div class="user-bio-container">
  <h2 class="h2-bio">Bio</h2>
  <p><%= @user.bio %></p>
</div>

<div class="user-posts-container">
  <h2>Recent Posts</h2>

  <ul>
    <% @user.most_recent_posts.includes(:comments, :likes).each do |post| %>
      <li class="posts-container">
        <h3><%= "Post ##{post.id}" %></h3>
        <h5><%= post.title %></h5>
        <p class="post-text"><%= post.text %></p>
        <p class="post-metadata">
          <span class="comments-count">Comments: <%= post.comments.count %></span>
          <span class="likes-count">Likes: <%= post.likes.count %></span>
        </p>
      </li>
    <% end %>
  </ul>
</div>

<div class="bottom-button">
  <%= button_to 'See All Posts', user_posts_path(@user), method: :get, class: 'last-btn' %>
</div>